inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - "*.gemspec"

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RegexpLiteral:
  Exclude:
    - "spec/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/SymbolArray:
  Exclude:
    - "lib/popcorn/cli.rb"
Style/HashSyntax:
  Exclude:
    - "Rakefile"

Lint/UselessAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Metrics/AbcSize:
  Exclude:
    - "lib/popcorn/cli.rb"
Metrics/LineLength:
  Max: 150
Metrics/ClassLength:
  Max: 200
