inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - "*.gemspec"

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "lib/popcorn/cli.rb"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Max: 150

Security/Eval:
  Exclude:
    - "spec/spec_helper.rb"

Style/BracesAroundHashParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "Rakefile"
Style/RegexpLiteral:
  Exclude:
    - Guardfile
    - "spec/**/*"
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Exclude:
    - "lib/popcorn/cli.rb"
